name: Run UI tests in test repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Import to XRay
        id: xray
        uses: mikepenz/xray-action@v3.1.1
        with:
          username: ${{ secrets.CLIENT_ID }}
          password: ${{ secrets.CLIENT_SECRET }}
          testFormat: "cucumber"
          testPaths: "**/cucumber/*.json"
          projectKey: "AC"

      - name: Publish XRay artifact
        shell: sh
        run: |
          url=https://sainsburys-tech.atlassian.net/browse/${{ steps.xray.outputs.testExecKey }}
          echo "__Created Test Execution [${{ steps.xray.outputs.testExecKey }}]($url)__." >> $GITHUB_STEP_SUMMARY

        


          
