name: Run UI tests in test repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  token: ""
  
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Get Token
        run: |
         token=$(curl -L \
            -X POST \
            -H "Content-Type: Application/Json" \
            -d "{ \"client_id\": \"${{ secrets.CLIENT_ID }}\",\"client_secret\": \"${{ secrets.CLIENT_SECRET }}\" }" \
            https://xray.cloud.getxray.app/api/v1/authenticate)

            echo "XRAY_TOKEN=$(echo $token)" >> $GITHUB_ENV

      - name: Publish to Xray
        run: |
          curl -L \
          -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $XRAY_TOKEN" \
          -d @"cucumber.json" \
          https://xray.cloud.getxray.app/api/v1/import/execution/cucumber

          
