name: Run UI tests in test repo

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Get Token
        run: |
         token=$(curl -L \
            -X POST \
            -H "Content-Type: Application/Json" \
            -d "{ \"client_id\": ${{ secrets.CLIENT_ID }},\"client_secret\": ${{ secrets.CLIENT_SECRET }} }" \
            https://xray.cloud.getxray.app/api/v1/authenticate)

          echo token
          echo $token

          
